services:
  app:
    build: .
    volumes:
      - ./html/:/var/www/html
  
  nginx:
    image: nginx:alpine
    ports:
      - 9090:80
    volumes:
      - ./html/:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
